In [1]:
import pandas as pd
import requests as rq
from bs4 import BeautifulSoup
import json

In [33]:
url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date=20210318&stockNo=2330'
response = rq.get(url)
_json_ = json.loads(response.text)
tw2317 = pd.DataFrame(_json_.get('data'),columns=_json_.get('fields'))
tw2317

,日期,成交股數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,成交筆數
0,110/03/02,"57,792,973","35,565,213,485",621.00,622.00,609.00,609.00,+3.00,"71,325"
1,110/03/03,"61,171,387","37,550,028,241",609.00,622.00,601.00,622.00,+13.00,"57,677"
2,110/03/04,"75,508,388","45,662,897,489",609.00,611.00,601.00,601.00,-21.00,"143,916"
3,110/03/05,"85,579,527","50,968,119,396",588.00,605.00,584.00,601.00,0.00,"127,693"
4,110/03/08,"47,676,630","28,737,004,484",608.00,610.00,598.00,598.00,-3.00,"84,570"
5,110/03/09,"74,471,341","43,957,092,621",585.00,595.00,585.00,595.00,-3.00,"119,867"
6,110/03/10,"41,735,443","24,904,320,192",601.00,601.00,593.00,597.00,+2.00,"54,196"
7,110/03/11,"55,462,783","33,584,884,382",596.00,612.00,595.00,609.00,+12.00,"47,948"
8,110/03/12,"33,876,990","20,780,886,905",615.00,618.00,609.00,614.00,+5.00,"36,145"
9,110/03/15,"29,767,904","18,194,081,208",614.00,614.00,609.00,611.00,-3.00,"26,753"
10,110/03/16,"37,780,820","23,074,187,740",610.00,613.00,607.00,613.00,+2.00,"37,573"
11,110/03/17,"43,942,131","26,638,906,800",612.00,612.00,602.00,604.00,X0.00,"68,585"
12,110/03/18,"30,223,846","18,286,667,342",606.00,609.00,602.00,602.00,-2.00,"31,677"

In [22]:
response.text

'{"stat":"OK","date":"20210318","title":"110年03月 2317 鴻海             各日成交資訊","fields":["日期","成交股數","成交金額","開盤價","最高價","最低價","收盤價","漲跌價差","成交筆數"],"data":[["110/03/02","54,679,187","6,208,416,490","114.50","114.50","112.00","112.00"," 0.00","24,377"],["110/03/03","90,671,041","10,385,729,569","113.00","116.00","112.00","115.50","+3.50","36,128"],["110/03/04","79,491,784","9,055,229,129","115.50","116.00","112.00","114.50","-1.00","30,614"],["110/03/05","87,263,439","10,007,886,347","113.50","116.00","112.50","115.00","+0.50","34,097"],["110/03/08","54,725,412","6,277,482,760","116.00","116.50","113.00","113.50","-1.50","23,284"],["110/03/09","44,151,477","5,019,110,304","113.00","115.00","112.00","115.00","+1.50","20,125"],["110/03/10","49,011,206","5,676,662,482","116.00","117.00","115.00","115.50","+0.50","20,545"],["110/03/11","76,015,788","8,894,298,610","116.50","118.00","116.00","117.00","+1.50","36,312"],["110/03/12","97,811,913","11,662,163,611","117.50","120.00","117.50","120.00","+3.00","51,423"],["110/03/15","70,166,127","8,428,413,588","120.00","122.00","118.50","121.00","+1.00","35,682"],["110/03/16","93,898,518","11,496,180,042","121.50","123.50","121.00","123.00","+2.00","46,078"],["110/03/17","145,610,279","18,331,370,516","123.50","128.00","123.00","126.00","+3.00","75,496"],["110/03/18","139,458,505","18,102,452,005","128.00","131.50","128.00","129.50","+3.50","70,643"]],"notes":["符號說明:+/-/X表示漲/跌/不比價","當日統計資訊含一般、零股、盤後定價、鉅額交易，不含拍賣、標購。","ETF證券代號第六碼為K、M、S、C者，表示該ETF以外幣交易。"]}'